name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: evenOrOdd test
      id: evenorodd-test
      with:
        test-name: evenOrOdd test
        setup-command: sudo -H pip3 install pytest
        command: pytest main_test.py
        timeout: 10
        max-score: 1
  run-autograding-tests:
    runs-on: ubuntu-latest
    needs: run-tests
    #if: github.actor != 'github-classroom[bot]'
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: evenOrOdd test
      id: evenorodd-test
      uses: education/autograding-command-grader@v1
      with:
        test-name: evenOrOdd test
        setup-command: sudo -H pip3 install pytest
        command: pytest main_test.py
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        EVENORODD-TEST_RESULTS: "${{steps.evenorodd-test.outputs.result}}"
      with:
        runners: evenorodd-test
